# Generated by Django 3.2.9 on 2023-07-19 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=200)),
                ('material', models.CharField(max_length=200)),
                ('mass_percent', models.FloatField()),
                ('amt_in_batch', models.FloatField()),
                ('specific_gravity', models.FloatField()),
                ('vol_mL', models.FloatField()),
                ('vol_percent', models.FloatField()),
                ('vol_per_gallon', models.FloatField()),
                ('lbs_in_gallon', models.FloatField()),
                ('cost_per_pound', models.FloatField()),
                ('cost_per_gallon', models.FloatField()),
                ('cost_per_oz', models.FloatField()),
                ('cost_per_bottle', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
