# Generated by Django 3.2.9 on 2023-08-03 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesOrder',
        ),
    ]
